### ISSUE TITLE
use integer type?

### ISSUE THREAD

**Issue by jpetey75** [lambtron/tap-clubspeed#1]
@lambtron can we use integers for some things instead of number so there isn't the `.0` at the end of the numbers in the database?

for example, this could be an int: https://github.com/lambtron/tap-clubspeed/blob/master/tap_clubspeed/schemas/checks.json#L10

if that's possible let me know i can help figure out which columns should be integers vs numbers

**Comment by lambtron** [comment]
yes we should prob go through and figure out which ones are integer vs. number. the unfortunate thing is that there is no easy to way to do this, except comb through clubspeed's not-very-great documentation (many data types were inconsistent to the point where i had to come across it organically during a sync). this also unfortunately fell to the bottom of the priority list.

when i have some time, i can go through and make sure all of these data types are properly set.

**Comment by jpetey75** [comment]
If it's really annoying let's skip it and leave as-is.
They are pretty good already and I can fix the ones i really need to be
integers in my queries.
Peace,

Jake Peterson
Bard Analytics <https://bardanalytics.com>
(415) 621-9508

**Comment by lambtron** [comment]
i made this change so the new tables should be fine!
